/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package javaproject;

import org.junit.jupiter.api.Test;


import static org.junit.jupiter.api.Assertions.*;

class AppTest {
    @Test
    public void testComptarElemets() {
        App gestor = new App(new int[] {2, 4, 6});
        assertEquals(3, gestor.comptarElements());
    }
    @Test
    public void testComptarElemets1() {
        App gestor = new App(new int[] {3, 4, 6});
        assertEquals(3, gestor.comptarElements());
    }
    @Test
    public void testComptarArrayBuit() {
        App gestor = new App(new int[] {});
        assertEquals(0, gestor.comptarElements());
    }
    @Test
    public void testRetornarTercer() throws Exception {
        App gestor = new App(new int[] { 8, 3});
        assertEquals(3, gestor.retornarTercer());
    }
    @Test
    public void testSumaElements() throws Exception {
        App gestor = new App(new int[] {1, 2, 3});
        assertEquals(6, gestor.sumaElements());
    }
    @Test
    public void testMitjanaElements() throws Exception {
        App gestor = new App(new int[] {1, 2, 3});
        assertEquals(2, gestor.mitjanaElements());
    }
}
